# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

#gems:         ['jekyll-paginate', 'jekyll-lunr-js-search']
gems:         ['jekyll-paginate']

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"
toc_levels:   1..3 # TOC # 2015/11/29

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#Site config
title: Hoàng Đắc Viết Web Design Mobile App Marketing Smarthome IoT
description: Hoangdacviet DevOps Engineer Fullstack Developer⭐ Web Design Mobile App Marketing Startup Smarthome IoT
keywords: Deep Learning
url: https://hoangdacviet.github.io
feed: /atom.xml
favicon: /images/favicon.png

#Nav config
nav:
  - text: HOME
    url: /index.html
  - text: CATEGORIES
    url: /categories.html
  - text: ARCHIVES
    url: /archives.html
  - text: LINKS
    url: /links.html
  - text: SEARCH
    url: /search.html
  - text: ABOUT ME
    url: /about.html

#Author config
author:
    name: hoangdacviet
    email: hoangdacviet@gmail.com
    imageLink: /images/header2.jpg
    simpleIntro: Hi world~
    detailIntro:
      <p>I am working as machine learning/deep learning engineer.</p>
      <p>This blog is used to organise interesting papers, projects, websites, blogs and my reading/study notes.</p>
      <p>Feel free to send PRs or open issues to help maintain this blog&#58; https://github.com/hoangdacviet/hoangdacviet.github.io</p>
      <p></p>

#You can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-pinterest
    url: http://www.pinterest.com/hoangdacviet
  - class: icon-facebook
    url: https://www.facebook.com/hoangdacviet
  - class: icon-github-alt
    url: https://github.com/hoangdacviet/
  - class: icon-twitter
    url: https://twitter.com/hoangdacviet
  - class: icon-linkedin
    url: https://www.linkedin.com/in/hoangdacviet

#Links
customLinks:
  - item:
    - text: Kome Cafe  Rang Xay nguyên Chất
      url: https://komecafe.blogspot.com
    - text: Công Ty TNHH Kami
      url: https://kami.vn
    - text: Kome SmartHome IoT
      url: https://iot.kome.top
    - text: SvTre.com LLC
      url: https://svtre.com
    message: HoangDacViet Business
  - item:
    - text: KomeCafe on Github
      url: https://github.com/KomeCafe
    - text: SvTre on Github
      url: https://github.com/SvTreDev
    message: Resources
  - item:
    - text: Công Ty Xây Dựng Họp Đại Thành
      url: https://hopdaithanh.com
    - text: Công Ty Ống Gió Tân Thành
      url: https://onggiotanthanh.com
    - text: Công Ty Ống Gió Đức Tín
      url: https://onggioductin.com
    message: Partners & Customers

googleAnaly:
  config: true
  id: UA-6792430-1

#baidu tongji
baiduTongji:
  config: false
  id:  9144251ce5a4f4019de4bc601b9b490b

#comment config
disqus:
  config: true
  id: handong1587

duoshuo:
  config: false
  id: null

#baidu share config
baiduShare:
  config: false

# lunr search
lunr_search:
  excludes: [rss.xml, atom.xml]
  stopwords: "stopwords.txt"
  min_length: 3
  js_dir: "javascript"
